title: struggle.dev

tagline: Solving everyday problems of a developer

description: > # this means to ignore newlines until "show_excerpts:"
  A blog highlighting and solving the everyday problems of a developer.
  Includes  posts in the categories of coding, reversing, machine learning, home automation and more.

show_excerpts: false # set to true to show excerpts on the homepage

google_analytics: UA-XXXXXXXX

matomo:
  uri: http://example.com
  site_id: 1337

struggle:
  date_format: "%-d %B %Y"
  skin: light

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: struggle

#paginate: 5
#paginate_path: "/posts/page:num/"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-autoprefixer

 # jekyll seo tag: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md