title: struggle.dev
tagline: Solving everyday problems of a developer
description: > # this means to ignore newlines until "show_excerpts:"
  A blog highlighting and solving the everyday problems of a developer.
  Includes  posts in the categories of coding, reversing, machine learning, home automation and more.

# set to true to show excerpts on the homepage
show_excerpts: true

# Set this to true to get LaTeX math equation support
use_math: true

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
show_image: true

# Set this to true to turn on annotations with hypothes.is (https://web.hypothes.is/)
annotations: false

# Set this to true to display tags on each post
show_tags: true

#google_analytics: UA-XXXXXXXX

#matomo:
#  uri: http://example.com
#  site_id: 1337

struggle:
  date_format: "%-d %B %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - about.md
#   - tags.html

# Build settings
theme: jekyll-struggle

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

comments: true

badges: true

# This specifies what badges are turned on by default for notebook posts.
default_badges:
  github: true
  binder: true
  colab: true

permalink: pretty

# collections:
#   pages:
#     output: true
#     permalink: /:path/

plugins:
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

  # jekyll seo tag: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

paginate: 5
paginate_path: /:num/

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: list-group
  sublist_class: sublist-toc-test
  item_class: list-group-item
  item_prefix: toc-
