name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2        

      - name: Dump Github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"

      - name: Show Version
        run: echo ${{steps.version.outputs.prop}}

      - name: Get Ruby Version
        uses: senmu/download-json-property-action@v1.0.0
        id: ruby-version
        with:
          url: "https://pages.github.com/versions.json"
          property_path: ruby

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.value }} # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build
        run: bundle exec jekyll build --incremental
      
      # Deleting a package/yanking a gem on Github via CLI is not allowed
      #- name: Yank Gem on Github
      #  if: "!contains(github.ref, 'refs/tags/v')"
      #  continue-on-error: true
      #  run: |
      #    mkdir -p $HOME/.gem
      #    touch $HOME/.gem/credentials
      #    chmod 0600 $HOME/.gem/credentials
      #    printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      #    gem yank ${{ github.event.repository.name }} -v ${{steps.version.outputs.prop}} --host "https://rubygems.pkg.github.com/${{github.repository_owner}}"
      #  env:
      #    GEM_HOST_API_KEY: "${{secrets.GITHUB_TOKEN}}"
          
      - name: Delete Gem on Github
        uses: JackHowa/delete-github-package-versions@v0.4.9
        with:
          names: ${{ github.event.repository.name }}
          semver-pattern: ${{steps.version.outputs.prop}}
          keep: 0

      # https://github.com/marketplace/actions/release-gem-to-github-packages
      - name: Publish Gem to Github
        uses: jstastny/publish-gem-to-github@master
        if: "!contains(github.ref, 'refs/tags/v')"
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: twsl
      
      - name: Yank Gem
        if: contains(github.ref, 'refs/tags/v')
        continue-on-error: true
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem yank ${{ github.event.repository.name }} -v ${{steps.version.outputs.prop}}
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
          
      # https://github.com/dawidd6/action-publish-gem
      - name: Publish Gem
        uses: dawidd6/action-publish-gem@v1.2.0
        if: contains(github.ref, 'refs/tags/v')
        with:
          # Rubygems.org API key
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
          # GitHub Packages token, not used, already pushed in previous step
          #github_token: ${{secrets.GITHUB_TOKEN}}
