name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"

      - run: echo ${{steps.version.outputs.prop}}

      - uses: senmu/download-json-property-action@v1.0.0
        id: ruby-version
        with:
          url: "https://pages.github.com/versions.json"
          property_path: ruby

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.value }} # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: bundle exec jekyll build --incremental

      #- name: Delete GitHub Packages Versions
      #  uses: WPMedia/delete-github-package-versions@v0.4.10
      #  with:
      #    semver-pattern: "=0.0.1" #${{steps.version.outputs.prop}}
      #    token: ${{secrets.GITHUB_TOKEN}}
      #    names: |
      #      struggle

      # https://github.com/marketplace/actions/release-gem-to-github-packages
      - name: Publish Gem to Github
        continue-on-error: true
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: twsl

      # https://github.com/dawidd6/action-publish-gem
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1.2.0
        if: contains(github.ref, 'refs/tags/v')
        with:
          # Rubygems.org API key
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
          # GitHub Packages token
          github_token: ${{secrets.GITHUB_TOKEN}}
